'Type: Dependencies':
  - '(?i\\deps)'

'Type: Documentation':
  - (?i)(documentation|docs)

'Type: GHA':
  - (?i)(gha|github action)

'Type: Infrastructure':
  - '(dependencies|dependency|deps|documentation|docs|gha|github action|testing|tests|coverage)'

'Type: Testing':
  - '(testing|tests|coverage)'

'Type: Bug':
  - '(bug|patch|fix)'

'Type: Enhancement':
  - '(feature)'

'Type: Performance':
  - '(performance)'

'Type: Tech Debt':
  - '(debt)'

'Type: Question':
  - '(question)'
