'Type: Dependencies':
  - requirements/stratify.yml
  - requirements/py*.yml
  - requirements/pypi*.txt
  - requirements/locks/py*.txt
  - '(dependencies|deps|dependency)'

'Type: Documentation':
  - README.md
  - index.ipynb
  - '(documentation|docs)'

'Type: GHA':
  - .github/*.yml
  - .github/**/*.yml

'Type: GHA':
  - '(gha|github action)'

'Type: Infrastructure':
  - '(dependencies|dependency|deps|documentation|docs|gha|github action|testing|tests|coverage)'

'Type: Testing':
  - src/stratify/tests/*
  - '(testing|tests|coverage)'

'Type: Bug':
  - '(bug|patch|fix)'

'Type: Enhancement':
  - '(feature)'

'Type: Performance':
  - '(performance)'

'Type: Tech Debt':
  - '(debt)'

'Type: Question':
  - '(question)'
