'Type: Dependencies':
  - requirements/stratify.yml
  - requirements/py*.yml
  - requirements/pypi*.txt
  - requirements/locks/py*.txt

'Type: Documentation':
  - README.md
  - index.ipynb

'Type: GHA':
  - .github/*.yml
  - .github/**/*.yml

'Type: Infrastructure':
  - '*'

'Type: Testing':
  - src/stratify/tests/*
