language: minimal
dist: xenial

env:
  matrix:
    - PYTHON_VERSION="2.7"
    - PYTHON_VERSION="3.6"
    - PYTHON_VERSION="3.7"

install:
  # Install miniconda
  # -----------------
  - echo "Installing miniconda"
  - export CONDA_BASE="https://repo.continuum.io/miniconda/Miniconda"
  - if [[ "${PYTHON_VERSION}" == 2* ]]; then
      wget --quiet "${CONDA_BASE}2-latest-Linux-x86_64.sh" -O miniconda.sh;
    else
      wget --quiet "${CONDA_BASE}3-latest-Linux-x86_64.sh" -O miniconda.sh;
    fi
  - bash miniconda.sh -b -p ${HOME}/miniconda
  - export PATH="${HOME}/miniconda/bin:${PATH}"

  # Create the basic testing environment
  # ------------------------------------
  - echo "Configure conda and create an environment"
  - conda config --set always_yes yes --set changeps1 no
  - conda config --set show_channel_urls True
  - conda config --add channels conda-forge
  - conda update --quiet conda
  - ENV_NAME="test-environment"
  - conda create --quiet -n ${ENV_NAME} python=${PYTHON_VERSION} pip
  - source activate ${ENV_NAME}

  # Customise the testing environment
  # ---------------------------------
  - echo "Install python-stratify dependencies"
  - conda install -n ${ENV_NAME} --file requirements.txt --file requirements-dev.txt

  #  Output debug info.
  - conda list -n ${ENV_NAME}
  - conda list -n ${ENV_NAME} --explicit
  - conda info -a

  # Enable coverage for Cython.
  - export CYTHON_COVERAGE=1

  # Install python-straty.
  - pip install -e .

script:
  - pytest -ra --pyargs stratify --cov

after_success: coveralls
